# Generated by Django 3.2.6 on 2022-03-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0002_post_c_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edit',
            field=models.IntegerField(default=0),
        ),
    ]
