# Generated by Django 3.2.6 on 2022-03-14 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0003_post_edit'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=16)),
                ('singup_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('relase_date', models.DateField(auto_now_add=True)),
                ('rating', models.IntegerField()),
                ('status', models.CharField(choices=[('R', 'Reviewed'), ('E', 'Error'), ('N', 'Not Reviewed'), ('A', 'Accepted')], max_length=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Forum.user')),
            ],
        ),
    ]
